### ISSUE TITLE
Uncaught TypeError: Return value of "PHPDocsMD\Console\PHPDocsMDCommand::execute()" must be of the type int, "null" returned. in vendor/symfony/console/Command/Command.php:261

### ISSUE THREAD

**Issue by HarasimowiczKamil** [victorjonsson/PHP-Markdown-Documentation-Generator#23]
```
PHP Fatal error:  Uncaught TypeError: Return value of "PHPDocsMD\Console\PHPDocsMDCommand::execute()" must be of the type int, "null" returned. in vendor/symfony/console/Command/Command.php:261
Stack trace:
#0 vendor/symfony/console/Application.php(911): Symfony\Component\Console\Command\Command->run()
#1 vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand()
#2 vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun()
#3 vendor/victorjonsson/markdowndocs/src/PHPDocsMD/Console/CLI.php(29): Symfony\Component\Console\Application->run()
#4 vendor/victorjonsson/markdowndocs/bin/phpdoc-md(15): PHPDocsMD\Console\CLI->run()
#5 {main}
  thrown in vendor/symfony/console/Command/Command.php on line 261
```

I think adding `return 0;` at the end of `PHPDocsMD\Console\PHPDocsMDCommand::execute` will solve the problem

**Comment by HarasimowiczKamil** [comment]
it will be nice to create new release in composer :wink:
